In [1]:
print("Hello World")



Hello World


In [2]:
import numpy as np


In [3]:
import numpy as np

data = np.array([12, 15, 18, 22, 30])

print("Average value (Mean):", np.mean(data))
print("Highest value (Max):", np.max(data))
print("Standard Deviation:", np.std(data))


Average value (Mean): 19.4
Highest value (Max): 30
Standard Deviation: 6.248199740725323


In [4]:
# Zeros
print(np.zeros((2, 3)))

# Ones
print(np.ones((2, 3)))

# Identity matrix
print(np.eye(3))

# Range of numbers
print(np.arange(0, 10, 2))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]


In [5]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])      # 10
print(arr[-1])     # 50
print(arr[1:4])    # [20 30 40]

10
50
[20 30 40]


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]
print(a - b)   # [-3 -3 -3]
print(a * b)   # [4 10 18]
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [7]:
# Random floats between 0 and 1
print(np.random.rand(3))

# Random integers
print(np.random.randint(1, 10, size=5))

[0.26882826 0.39963048 0.30039985]
[7 7 5 6 2]


In [8]:
arr = np.array([1, 2, 3, 4])

print(arr + 10)
print(arr * 2)

[11 12 13 14]
[2 4 6 8]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))
print(result)

[1 2 3 4 5 6]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])

parts = np.split(arr, 3)

print(parts)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [11]:
import pandas as pd

In [12]:
import pandas as pd

# Example 1: Create a DataFrame from a dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Paris"]
}
df = pd.DataFrame(data)
print(df)


      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris


In [13]:
# Example 2: Read a CSV file
df = pd.read_csv("sample.csv")
print(df.head())  # show first 5 rows


FileNotFoundError: [Errno 2] No such file or directory: 'sample.csv'

In [14]:
# Example 3: Filtering rows
young = df[df["Age"] < 30]
print(young)


    Name  Age      City
0  Alice   25  New York


In [15]:
# Example 4: Grouping and aggregation
grouped = df.groupby("City")["Age"].mean()
print(grouped)


City
London      30.0
New York    25.0
Paris       35.0
Name: Age, dtype: float64


In [16]:
# Example 5: Adding a new column
df["Age in 5 years"] = df["Age"] + 5
print(df)


      Name  Age      City  Age in 5 years
0    Alice   25  New York              30
1      Bob   30    London              35
2  Charlie   35     Paris              40


In [ ]:
b